###Get the service document
http://localhost:4004/odata/v4/CatalogService 

###Get Service metadata document
http://localhost:4004/odata/v4/CatalogService/$metadata 

###Get All employee data
http://localhost:4004/odata/v4/CatalogService/EmployeeSet

###Get All employee data with odata v2
http://localhost:4004/v2/odata/v4/CatalogService/EmployeeSet

###Pagination - load data chunk by chunk
http://localhost:4004/odata/v4/CatalogService/EmployeeSet?$top=2

###Filtring of data = where Condition
http://localhost:4004/odata/v4/CatalogService/EmployeeSet?$filter=salaryAmount ge 1000000

###Counting Records
http://localhost:4004/odata/v4/CatalogService/EmployeeSet/$count

###Get Single Record by Key
http://localhost:4004/odata/v4/CatalogService/EmployeeSet/{id}

###Get the PO and it's Items data together - Associations
http://localhost:4004/odata/v4/CatalogService/POs/74867AD200E41EDBA5D8B06885B04052?$expand=Items,PARTNER_GUID

###POST - To Create New Employee
POST http://localhost:4004/odata/v4/CatalogService/EmployeeSet
Content-Type: application/json

{
  "nameFirst": "Salim",
  "nameMiddle": "",
  "nameLast": "Anub",
  "nameInitials": null,
  "sex": "M",
  "language": "E",
  "phoneNumber": "224875468",
  "email": "salim.anub@itelo.info",
  "loginName": "SALIM",
  "Currency": {"code":"USD"},
  "salaryAmount": 5549,
  "accountNumber": "181228339",
  "bankId": "510440655",
  "bankName": "My Bank"
}

###PATCH to update the employee data
PATCH http://localhost:4004/odata/v4/CatalogService/EmployeeSet/{ID}
Content-Type: application/json

{
    "salaryAmount": 9654896
}

###DELETE Employee data
DELETE http://localhost:4004/odata/v4/CatalogService/EmployeeSet/[ID]

###POST - To Create New POs
POST http://localhost:4004/odata/v4/CatalogService/POs
Content-Type: application/json

  {
    "NODE_KEY": "74867AD200E41EDBA5D8B0C98DC28052",
    "PO_ID": "300000000",
    "PARTNER_GUID_NODE_KEY": "74867AD200E41EDBA5D8B06885B04052",
    "GROSS_AMOUNT": 3913.91,
    "NET_AMOUNT": 3289.00,
    "TAX_AMOUNT": 624.91,
    "LIFECYCLE_STATUS": "N",
    "OVERALL_STATUS": "P"
  }
###Get Single PO
http://localhost:4004/odata/v4/CatalogService/POs/74867AD200E41EDBA5D8B0C98DC28052

###POST Calling an action
POST http://localhost:4004/odata/v4/CatalogService/POs/74867AD200E41EDBA5D8B06885B04052/boost
Content-Type: application/json

{}

###GET Calling CAP functions
GET http://localhost:4004/odata/v4/CatalogService/POs/74867AD200E41EDBA5D8B06885B04052/largestOrder()

###Getting Product data from CDS View
GET http://localhost:4004/odata/v4/MyService/ProductOrdersSet/{Id}

###Get the lazy loading
GET http://localhost:4004/odata/v4/MyService/ProductOrdersSet/{Id}/PO_ORDERS

###Complete custom entity
GET http://localhost:4004/odata/v4/MyService/ReadEmployeeSrv